### ISSUE TITLE
Notifications for translators via Pushbullet

### ISSUE THREAD

**Issue by ja-som** [TilesOrganization/resources#2]
Hi dev and translators :)
I made a channel on Pushbullet for Tiles Localization, I use it for a while. If you use Pushbullet and something new is uploaded here on GitHub, you receive a notification, so it will be easier to know when you should translate it :)

https://www.pushbullet.com/channel?tag=tileslocalization

Also, I would like to ask you all, when you edit your files, please add your language code to commit changes title, e.g. "Update strings.xml **SK**"
Thanks

@marci4 @rascarlo @zalcso @Garduna1976 @rodrigoswz @cyberon @lkvnclh

**Comment by rascarlo** [comment]
@ja-som great idea! let's also ping @nezorflame @syokkendesuyo @JuanMiguelML @Younes-L

**Comment by Younes-L** [comment]
Hi, I am currently using IFTTT to get notified on Telegram, but I will look into this. Thanks !

**Comment by marci4** [comment]
Quess we don't need it with our telegram bot right?

**Comment by rascarlo** [comment]
@marci4 some might still use pushbullet: @ja-som had a good idea to set up a channel for this, let's keep it
