### ISSUE TITLE
LiveDisplay on Lineage OS?

### ISSUE THREAD

**Issue by ja-som** [TilesOrganization/resources#3]
Hi,
it is possible to add a tile for LiveDisplay on Lineage OS?

https://github.com/LineageOS/android_packages_apps_CMParts/tree/cm-14.1/src/org/cyanogenmod/cmparts/livedisplay

Thanks :)

**Comment by rascarlo** [comment]
Although it might be possible, it is not something I am willing to do.
There are few reasons why:
- I don't want to add custom roms specific tiles.
- I don't want to step on the rom's toes.
- I am sure once the development is out of the early stages,  more tiles will be added to the rom's frameworks.
- I run stock android on my devices and I will have no ways to test the app unless I flash a custom rom. I prefer to test and run all my projects on stock android for compatibility reasons.

But thanks for your question

**Comment by ja-som** [comment]
OK, I understand ;)
Thanks for your reply.
